name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Firebase CLI
      - run: npm install -g firebase-tools

      # Run the build process
      - run: npm ci && npm run build
        env:
          NEXT_PUBLIC_CLOUD_VERSION: ${{ secrets.NEXT_PUBLIC_CLOUD_VERSION }}
          NEXT_PUBLIC_PLAN_KEY: ${{ secrets.NEXT_PUBLIC_PLAN_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_STRIPE_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY }}

      # Save the service account key to a file and set GOOGLE_APPLICATION_CREDENTIALS
      - run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DATAKNOBS_PUBLIC }}" > service-account.json
      - run: export GOOGLE_APPLICATION_CREDENTIALS="service-account.json"
      
      # Authenticate Firebase CLI using the service account
      - run: firebase use --add

      # Enable the webframeworks experiment
      - run: firebase experiments:enable webframeworks

      # Deploy to the specific hosting target
      - run: firebase deploy --only hosting:kreatewebsites-main
